name: WakaTime status update

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats 
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"
          COMMIT_MSG: "docs(wakatime): update code activity :alien:"
